### ISSUE TITLE
Forbidden (Permission denied): /admin/feedreader/feed/

### ISSUE THREAD

**Issue by Kulikovpavel** [ahernp/django-feedreader#12]
Hello

conf:
Django==1.9.2
django-feedreader==1.3.6

I did INSTALLED_APPS, ulrs, makemigration and migrate, collectstatic

But when open '/admin/feedreader' i got "403 Forbidden error"
Without admin, just on '/feedreader' i got only non-styled links
http://puu.sh/njEfM/f870cd1160.png

Where did i wrong?

**Comment by ahernp** [comment]
Hi Pavel,

I think you just need to be logged in to Django, on your test system, with
an account that has permission to use the Django admin. If you
set Superuser status on your test account that that will bypass the
permissions checks.

As no feeds have been subscribed to, /feedreader just shows an empty page.
The image you sent looks like the footer of the /feedreader page. I don't
know why the image has a blue background.

Also I've tested django-feedreader with version 1.9.1 of Django but not
1.9.2.


Paul Ahern
+44 (0)776 037 2573
ahernp (skype)
www.ahernp.com

**Comment by Kulikovpavel** [comment]
This account have permission to use admin panel.

Relog dont work either

**Comment by ahernp** [comment]
So when you log in to /admin do you see a section for Feedreader models?

If so, do you have specific User permissions (under /admin/auth/user/)?

**Comment by Kulikovpavel** [comment]
Thanks, it was user rights.
Newly created superuser worked good. Thanks again.
