### ISSUE TITLE
Please upgrade to Django 2.0

### ISSUE THREAD

**Issue by EverettBuckley** [ahernp/django-feedreader#16]
Hello. Would it be possible for you to please upgrade this code to Django 2.0?

**Comment by ahernp** [comment]
Sure. I'll have a look at the weekend.

**Comment by ahernp** [comment]
I've updated [django-feedreader](https://github.com/ahernp/django-feedreader) to work with Django 2.0.3. The [package](https://pypi.python.org/pypi/django-feedreader/2.0.0) on PyPI has also been updated.

**Comment by EverettBuckley** [comment]
You are amazing! Thank you very, very much!
