### ISSUE TITLE
Please upgrade requirement to Django 2.1?

### ISSUE THREAD

**Issue by EverettBuckley** [ahernp/django-feedreader#18]
Thank you very much for writing this app. You are very talented.  I am sorry to bother you with this request, but I have been trying to use this app with other projects that are now using 2.1. Is it possible to update version that is in pypy to 2.1? I was able to install directly from this repo, but it appears that the pypy version is still using Django 2.0.

**Comment by EverettBuckley** [comment]
Thanks very much for all of the assistance that you gave me the last time I opened up an issue. I am very grateful!

**Comment by ahernp** [comment]
You are quite right, I forgot to upload the new version to PyPI. I have done so now: <https://pypi.org/project/django-feedreader/2.1.0/>
Thanks for letting me know.
