### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by Bachstelze** [ahernp/django-feedreader#24]
Which changes have to be done to fully support the [current Django version](https://docs.djangoproject.com/en/3.0/releases/3.0/)?

**Comment by ahernp** [comment]
I just needed to make a few tweaks. See https://github.com/ahernp/django-feedreader/commit/1d0c18cecb24cc7ad88824e93a1997e71925a767

**Comment by Bachstelze** [comment]
Thank you! I am going to test it.
