### ISSUE TITLE
the url setting should update?

### ISSUE THREAD

**Issue by renpj** [ahernp/django-feedreader#6]
I found the url setting
url(r'^feedreader/', include('feedreader.urls')),
should update to
url(r'^feedreader/', include('feedreader.urls'), namespace="feedreader"),
else, there is a error:
u'feedreader' is not a registered namespace.
I'm new in django, I'm not sure.

**Comment by ahernp** [comment]
Sorry for the delay in getting back to you, I am just back from a holiday. You are absolutely correct. I had this in my own installation but forgot to update the `django-feedreader` README. This has now been done. Thanks for letting me know.
