### ISSUE TITLE
 the "Loading" symbol always show

### ISSUE THREAD

**Issue by renpj** [ahernp/django-feedreader#7]
I notice that the "Loading" symbol always show when I open 127.0.0.1/feedreader
Is there something wrong?
![1](https://cloud.githubusercontent.com/assets/11707719/7105099/21bf9a96-e13a-11e4-9fda-be78e673bda2.png)

**Comment by ahernp** [comment]
The "loading" symbol is displayed while an Ajax call is waiting for a response from the server. If no response is received then it will display forever. I suggest checking the logs on your server to see if the latest request has failed.
