### ISSUE TITLE
The current URL, accounts/login/, didn't match any of these.

### ISSUE THREAD

**Issue by paolodina** [ahernp/django-feedreader#8]
Hi, I created a new virtualenv where experimenting with django-feedreader. I added `feedreader` to `INSTALLED_APPS` and changed `urls.py` adding `url(r'^feedreader/', include('feedreader.urls', namespace='feedreader'))` as said in the docs.

The output of `pip freeze` is:
```
Django==1.8
django-braces==1.4.0
django-feedreader==1.2.1
factory-boy==2.5.1
feedparser==5.1.3
mock==1.0.1
pytz==2015.4
six==1.9.0
```
The weird thing (a redirect attempt to the login page) happens trying to access `http://127.0.0.1:8000/feedreader/` as anonymous user.

```
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/accounts/login/?next=/feedreader/
Using the URLconf defined in project.urls, Django tried these URL patterns, in this order:
^admin/
^feedreader/
The current URL, accounts/login/, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```
When I'm already authenticated everything is ok. I wonder why the error happens and why it's required to be an authenticated user to see that page, and finally what I'm doing wrong.

**Comment by ahernp** [comment]
Hi Paolo,

You are not doing anything wrong. I designed `django-feedreader` to require an authenticated user. My reason being that using this tool makes updates to your database, so it seemed best to restrict access to it.

For example, scrolling through a list of unread Entries in `django-feedreader` marks them as read. There are also controls on the main page which cause your server to immediately read one or many Feeds looking for new Entries.

However, if you want to try out `django-feedreader` without an authenticated user then remove the `LoginRequiredMixin` from the class declarations in `feedreader/views.py` (this should be found in the site-packages directory of your virtual environment).

The redirect to the login page is something Django does by default. `accounts/login` is the default login url. If you add `url('^accounts/', include('django.contrib.auth.urls')),` to your `urls.py` then a login page should appear and let you log in if you are not authenticated.

I hope that I have answered all of your questions.

**Comment by paolodina** [comment]
Thank you very much for the detailed explanation, it makes a lot of sense!

**Comment by Nidhibarthwal** [comment]
Add in your urls.py
url('^accounts/', admin.site.urls),

**Comment by blairg23** [comment]
I had to do a `./manage.py collectstatic` to get the `django-rest-swagger` docs working correctly with authentication (without any of the recommendations previously mentioned, cos I had tried those to no avail previously).

**Comment by tefatt** [comment]
> Add in your urls.py
> url('^accounts/', admin.site.urls),

Worked for me as well.
